import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./providers/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
